export const emojiList = [
  { name: '[笑掉牙]', file: 'xiaodiaoya.webp' },
  { name: '[可爱]', file: 'keai.webp' },
  { name: '[冷酷]', file: 'lengku.webp' },
  { name: '[闭嘴]', file: 'bizui.webp' },
  { name: '[生气]', file: 'shengqi.webp' },
  { name: '[惊恐]', file: 'jingkong.webp' },
  { name: '[瞌睡]', file: 'keshui.webp' },
  { name: '[大笑]', file: 'daxiao.webp' },
  { name: '[爱心]', file: 'aixin.webp' },
  { name: '[坏笑]', file: 'huaixiao.webp' },
  { name: '[飞吻]', file: 'feiwen.webp' },
  { name: '[疑问]', file: 'yiwen.webp' },
  { name: '[开心]', file: 'kaixin.webp' },
  { name: '[发呆]', file: 'fadai.webp' },
  { name: '[流泪]', file: 'liulei.webp' },
  { name: '[汗颜]', file: 'hanyan.webp' },
  { name: '[惊悚]', file: 'jingshu.webp' },
  { name: '[困~]', file: 'kun.webp' },
  { name: '[心碎]', file: 'xinsui.webp' },
  { name: '[天使]', file: 'tianshi.webp' },
  { name: '[晕]', file: 'yun.webp' },
  { name: '[啊]', file: 'a.webp' },
  { name: '[愤怒]', file: 'fennu.webp' },
  { name: '[睡着]', file: 'shuizhuo.webp' },
  { name: '[面无表情]', file: 'mianwubiaoqing.webp' },
  { name: '[难过]', file: 'nanguo.webp' },
  { name: '[犯困]', file: 'fankun.webp' },
  { name: '[好吃]', file: 'haochi.webp' },
  { name: '[呕吐]', file: 'outu.webp' },
  { name: '[龇牙]', file: 'ziya.webp' },
  { name: '[懵比]', file: 'mengbi.webp' },
  { name: '[白眼]', file: 'baiyan.webp' },
  { name: '[饿死]', file: 'esi.webp' },
  { name: '[凶]', file: 'xiong.webp' },
  { name: '[感冒]', file: 'ganmao.webp' },
  { name: '[流汗]', file: 'liuhan.webp' },
  { name: '[笑哭]', file: 'xiaoku.webp' },
  { name: '[流口水]', file: 'liukoushui.webp' },
  { name: '[尴尬]', file: 'ganga.webp' },
  { name: '[惊讶]', file: 'jingya.webp' },
  { name: '[大惊]', file: 'dajing.webp' },
  { name: '[不好意思]', file: 'buhaoyisi.webp' },
  { name: '[大闹]', file: 'danao.webp' },
  { name: '[不可思议]', file: 'bukesiyi.webp' },
  { name: '[爱你]', file: 'aini.webp' },
  { name: '[红心]', file: 'hongxin.webp' },
  { name: '[点赞]', file: 'dianzan.webp' },
  { name: '[恶魔]', file: 'emo.webp' },
];

export let emojiPage = {};
emojiList.forEach((item, index) => {
  if (!emojiPage[Math.floor(index / 30) + 1]) {
    emojiPage[Math.floor(index / 30) + 1] = [];
  }
  emojiPage[Math.floor(index / 30) + 1].push(item);
});
